# Mission 1

Below is a dictionary containing the number of French campuses that offer each kind of Wild Code School course.

wildcodeschool = {
   "data_analyst": 4,
   "data_scientist": 2,
   "dev_web": "13"
}

Find a way to only display the keys that have int values.

In [ ]:
#test
wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": "13"
}
wildcodeschool.keys()

dict_keys(['data_analyst', 'data_scientist', 'dev_web'])

In [ ]:
#solution
wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": "13"
}
int_keys = [key for key, value in wildcodeschool.items() if type(value) is int]
print(int_keys)

['data_analyst', 'data_scientist']

# Mission 2

For the same dictionary, find a way to display all the values that have a key that contains the letter "e".

In [ ]:
wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": "13"
}
#On commence par séparer le dic en une liste de tuples pour conserver les couples keys/value tout en obtenant 3 objets uniques sur lequel
#nous pourrons appliquer plus simplement notre itération pour trouver e dans les keys.
print(wildcodeschool.items())

for key, value in wildcodeschool.items():
  if "e" in key:
    print(value)


    #While (dictionnaire TRUE)
    #for key, in dictionnaire
    #if "e" in key
    #print([dictionnaire(key)])

  #for key in dictionnaire.keys

dict_items([('data_analyst', 4), ('data_scientist', 2), ('dev_web', '13')])
2
13

# Mission 3

Within the same dictionary, change the type of the value of the "dev_web" key to be an int. Then add a new key-value pair which will be "total_campus" : 19, using a **dictionary method**.

In [ ]:
wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": "13"
}


wildcodeschool ["dev_web"] = int (wildcodeschool["dev_web"])
wildcodeschool.update({"total_campus": 19})
print(wildcodeschool)

{'data_analyst': 4, 'data_scientist': 2, 'dev_web': 13, 'total_campus': 19}

# Mission 4

Take the dictionary generated from mission 3. Delete the key value pair :
- 'dev_web': 13 using a method
- 'total_campus': 19 using another method

In [ ]:
wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": "13",
  "total_campus": 19
}
del wildcodeschool["dev_web"]
wildcodeschool.pop("total_campus")
print(wildcodeschool)

{'data_analyst': 4, 'data_scientist': 2}

# Mission 5

Still within the dictionary generated from Mission 3, find a way to display the dictionary keys in alphabetical order.

In [ ]:
wildcodeschool =	{
  "data_scientist": 2,
  "total_campus": 19,
  "data_analyst": 4,
  "dev_web": "13"
}
keys = list(wildcodeschool.keys())
keys.sort()
print(keys)

['data_analyst', 'data_scientist', 'dev_web', 'total_campus']

# Mission 6

Create a script that returns the same elements as the **values()** method, as a list.

Example: for `{'a': 1, 'b': 2, 'c': 3}` it will create `[1, 2, 3]`

In [ ]:
#using a for loop here is not necessary
my_dict = {"Test": 21, "Z": "alphabet", "Thre": 3, "D": 4,}

my_list = []

for i in my_dict.values():
    my_list.append(i)

print(my_list)
print(type(my_list))

[21, 'alphabet', 3, 4]
<class 'list'>

In [ ]:
#This answer is simpler and more effective !
my_dict = {"Test": 21, "Z": "alphabet", "Thre": 3, "D": 4,}
my_list=list(my_dict.values())
print(my_list)
print(type(my_list))

[21, 'alphabet', 3, 4]
<class 'list'>