There is another object type we haven't talked about: `set`  
It looks like a `dictionary`, but it's not a dictionary.

In [ ]:
my_set = {"apple", "kiwi", "pineapple"}

In [ ]:
type(my_set)

set

Question : Why isn't `my_set` an object from the `dict` class ?

Answer : Because it a set. It doesn't have key/values pairs like a dictionnary, and it has curly braces {}

Another specificity from `set` object is that they cannot have two items with the same values.

Execute the cells below.

In [ ]:
a_set = {"banana", "lemon", "lemon", "cherry", "lemon", "strawberry", "lemon" }

In [ ]:
a_set

{'banana', 'cherry', 'lemon', 'strawberry'}

Question :  

Hom many items do the sets below have ?

To answer, you can use your knowledge or the `len()` function.

In [ ]:
this_set = {1, 2, 3, 1, 2, 4, 1, 4, 3, 5, 6, 8, 9, 8, 3, 7, 6, 8, 6, 8, 9}
len(this_set)

9

Question :  

Can a set contain elements with differents types ? Yes, as seen below

In [ ]:
# try to make a set with objects with different types here:
answer = {"hey", 2, True, 2.33}
print(answer)

{True, 2, 2.33, 'hey'}

Question :  

Using the list below, there is a simple way to know the amount of unique values from this list.

What is it ?

In [ ]:
# Try to count the amount of unique values from this list, in one line of code.

a_list = [1, 2, 3, 1, 2, 4, 1, 4, 3, 5, 6, 8, 9, 8, 3, 7, 6, 8, 6, 8, 9]
set(a_list)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

There are four collection data types in the Python programming language:

* `List` is a collection which is ordered and changeable. Allows duplicate members.
* `Tuple` is a collection which is ordered and unchangeable. Allows duplicate members.
* `Set` is a collection which is unordered, unchangeable, and unindexed. No duplicate members, but you can remove items and add new items.
* `Dictionary` is a collection which is ordered and changeable. No duplicate members.

Question :   
Find a way to access to the first value of `this_set`

In [ ]:
# This methods works, but we do not really access the first value of this_set.
this_set={"hey", 2, True, 2.33}
list_set=list(this_set)
print (list_set[0])

['hey', 2, 2.33, True]

In [ ]:
#Iterating seems a better idea
this_set={"hey", 2, True, 2.33}
for i in this_set:
  print(i)
  break

hey

Question :  
Find a way to add a value that will be unique in `a_set`

In [ ]:
a_set.add("blueberry")
print(a_set)

{'lemon', 'banana', 'strawberry', 'cherry', 'blueberry'}

Question :  
Now, you have to add the value from `this_set` to `a_set`:

In [ ]:
a_set={'lemon', 'banana', 'strawberry', 'cherry', 'blueberry'}
this_set=['hey', 2, 2.33, True]
a_set.update(this_set)
print(a_set)

{'hey', 2, 2.33, True, 'lemon', 'cherry', 'strawberry', 'blueberry', 'banana'}

Question :    

If you display a `set` object, it won't display with the same order you define it.

What can you say about the order the element are display ?

Answer :     Sets are a mutable collection of distinct (unique) immutable values that are unordered

Question :   

Find a way to display the elements that exist in both sets.

In [1]:
a_set = {"banana", "grapes", "cherry", "pineapple", "kiwi", "strawberry"}

b_set = {"lemon", "kiwi", "grapes", "blueberry", "watermelon"}

c_set=a_set.intersection(b_set)
print(c_set)

{'kiwi', 'grapes'}

There is other methods for `set` objects, that you can find [here](https://www.w3schools.com/python/python_ref_set.asp).